name: particle_clock
description: Mickel's entry for the Flutter Clock challenge.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^2.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    git:
      url: https://github.com/domesticmouse/flutter_clock
      path: flutter_clock_helper

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/palettes.json